services:

  django:
    build:
      context: .
      dockerfile: portfolio.Dockerfile
    container_name: portfolio_app
    restart: unless-stopped
    volumes:
      - static_volume:/app/static
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: portfolio_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/certs/erwan-nisol.freeboxos.fr:/certs:ro
      - static_volume:/static
    depends_on:
      - django

  tileserver:
    image: maptiler/tileserver-gl:latest
    container_name: portfolio_tileserver
    restart: unless-stopped
    volumes:
      - ./docker/tileserver-gl:/data
    command: >
      tileserver-gl --port 8080 --public_url /tiles/ --file /data/paris.mbtiles --verbose
    expose:
      - "8080"

volumes:
  static_volume:
